# Generated by Django 4.2.7 on 2024-03-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default=1, max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(choices=[("Man", "Man"), ("Woman", "Woman")], default="Man", max_length=31),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default=1, max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
